//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAIMC_MemberManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberMeeting
    {
        public int MemberMeetingID { get; set; }
        public Nullable<int> Meetingid { get; set; }
        public Nullable<int> SAIMC_Nr { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual Member Member { get; set; }
    }
}
