//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAIMC_MemberManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int SAIMC_Nr { get; set; }
        public string Invoice_Type { get; set; }
        public string Members_Rating { get; set; }
        public string Branch { get; set; }
        public string Title { get; set; }
        public string Initial { get; set; }
        public string Nickname { get; set; }
        public string Surname { get; set; }
        public string E_Mail { get; set; }
        public string MobilePhone { get; set; }
        public string ECSA { get; set; }
        public string Paid { get; set; }
        public string Balance { get; set; }
        public Nullable<bool> Haspaid { get; set; }
        public byte[] MemberQRCode { get; set; }
    }
}
