//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAIMC_MemberManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAIMCEntities11111 : DbContext
    {
        public SAIMCEntities11111()
            : base("name=SAIMCEntities11111")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<MemberMeeting> MemberMeetings { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<QRGeneration> QRGenerations { get; set; }
    }
}
